name: Release

on: push

permissions:
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-dist
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf \
            https://github.com/axodotdev/cargo-dist/releases/download/v0.7.1/cargo-dist-installer.sh | sh

      - name: Build
        run: |
          cargo dist build --tag=${{ github.ref_name }} --output-format=json > dist-manifest.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ github.ref_name }}
          path: |
            target/distrib/*
