name: Build

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-dist
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf \
            https://github.com/axodotdev/cargo-dist/releases/download/v0.7.1/cargo-dist-installer.sh | sh

      - name: Initialize cargo-dist
        run: cargo dist init --allow-dirty --no-interaction

      # Build for the host platform only
      - name: Build
        run: cargo dist build --output-format=json > dist-manifest.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: |
            target/distrib/*
